#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config external_bar               all:38:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.0          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0.3          \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                layout                     bsp          \
                                                        \
                mouse_modifier             ctrl         \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                2            \
                bottom_padding             2            \
                left_padding               2            \
                right_padding              2            \
                window_gap                 4

yabai -m space 1
yabai -m space 2
yabai -m space 3
yabai -m space 4
yabai -m space 5
yabai -m space 6
yabai -m space 7

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app='^TablePlus$'        manage=off layer=above
yabai -m rule --add app='^Preview$'          manage=off layer=above
yabai -m rule --add app='^Simulator$'          manage=off layer=above
yabai -m rule --add app='^qemu-system-aarch64$'          manage=off layer=above
yabai -m rule --add app='^emacs$' manage=on
yabai -m rule --add app='^alacritty$' manage=on

echo "yabai configuration loaded"
